[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "week02"
version = "0.0.1"
description = ""
dependencies = [
    "torch ==2.2.2",
    "notebook ==7.1.2",
    "optuna ==3.6.1",
    "wandb ==0.16.5",
    "numpy ==1.26.4",
    "matplotlib ==3.8.3",
]
